[package]
name = "bevy_rest_template"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
bevy-tokio-tasks = "0.14.0"
parking_lot = "0.12.3"
serde = "1.0.204"
tokio = "1.39.1"
warp = "0.3.7"
zenoh = "0.11.0"
